<!-- footer.inc -->
<footer class="footer-copyright">
  <p id="copyright">&copy; 2024 s1xkyriceBoi Inc. All rights reserved.</p>
  <div class="social-media-group">
    <a href="#"><img class="social-media" src="./images/logo/facebook.png" alt="Facebook" /></a>
    <a href="#"><img class="social-media" src="./images/logo/x.png" alt="X" /></a>
    <a href="#"><img class="social-media" src="./images/logo/instagram.png" alt="Instagram" /></a>
    <a href="#"><img class="social-media" src="./images/logo/youtube.png" alt="YouTube" /></a>
  </div>
</footer>
