<header>
  <nav class="nav">
    <div class="nav-left">
      <a href="index.php">
        <img src="./images/logo.svg" alt="Logo" />
      </a>
    </div>
    <div class="nav-right">
      <a href="index.php">Home</a>
      <a href="product.php">Store</a>
      <a href="enquire.php">Enquire</a>
      <a href="aboutUs.php">About Us</a>
      <a href="enhancements.php">Enhancements</a>
      <a href="enhancements2.php">Enhancements2</a>
    </div>
  </nav>
</header>